version: '3.8'

services:
  # 1. Base de données (Stocke les logs MLflow et les données métier)
  postgres:
    image: postgres:13
    container_name: mlops_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mlops_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mlops_net

  # 2. MLflow Tracking Server (Interface graphique & Registry)
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.7.1
    container_name: mlops_mlflow
    ports:
      - "5000:5000"
    environment:
      # MLflow va stocker ses métadonnées dans Postgres
      MLFLOW_BACKEND_STORE_URI: postgresql://user:password@postgres:5432/mlops_db
      MLFLOW_ARTIFACT_ROOT: /mlflow/artifacts
    command: >
      mlflow server
      --backend-store-uri postgresql://user:password@postgres:5432/mlops_db
      --host 0.0.0.0
      --default-artifact-root /mlflow/artifacts
    volumes:
      - ./mlflow_artifacts:/mlflow/artifacts # Stockage local des modèles (pour simplifier au début)
    depends_on:
      - postgres
    restart: always
    networks:
      - mlops_net

networks:
  mlops_net:

volumes:
  postgres_data: