services:
  postgres:
    image: postgres:13
    container_name: mlops_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mlops_db
    ports:
      - "5432:5432"
    networks:
      - mlops_net

  mlflow:
    build:
      context: .
      dockerfile: docker/Dockerfile.mlflow
    container_name: mlops_mlflow
    hostname: mlflow
    ports:
      - "5000:5000"
    environment:
      MLFLOW_BACKEND_STORE_URI: postgresql://user:password@postgres:5432/mlops_db
      MLFLOW_ARTIFACT_ROOT: /mlflow/artifacts
    command: mlflow server --backend-store-uri postgresql://user:password@postgres:5432/mlops_db --host 0.0.0.0 --port 5000 --default-artifact-root /mlflow/artifacts --allowed-hosts "mlflow,mlflow:5000,localhost,localhost:5000"
    volumes:
      - ./mlflow_artifacts:/mlflow/artifacts
    depends_on:
      - postgres
    restart: always
    networks:
      - mlops_net

  api:
    build:
      context: ./app
    container_name: mlops_api
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./mlflow_artifacts:/mlflow/artifacts
    depends_on:
      - mlflow
    networks:
      - mlops_net

  train:
    build:
      context: ./app
    container_name: mlops_trainer
    volumes:
      - ${PWD}:/app
      - ./mlflow_artifacts:/mlflow/artifacts
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    networks:
      - mlops_net
    command: python /app/ml_core/train.py

  frontend:
    image: python:3.9-slim
    container_name: mlops_frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "pip install streamlit requests && streamlit run app.py --server.port=8501 --server.address=0.0.0.0"
    networks:
      - mlops_net
    depends_on:
      - api

networks:
  mlops_net:
    driver: bridge